// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audits.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const flagManualAnomaly = `-- name: FlagManualAnomaly :one
INSERT INTO audits (
    id, utility_bill_id, auditor_id, is_manual_anomaly, manual_anomaly_reason,
    status, created_at, updated_at
) VALUES (
    $1, $2, $3, true, $4, 'PENDING_CORRECTION', NOW(), NOW()
)
ON CONFLICT (id) DO UPDATE
SET 
    is_manual_anomaly = true,
    manual_anomaly_reason = EXCLUDED.manual_anomaly_reason,
    status = 'PENDING_CORRECTION',
    updated_at = NOW()
RETURNING id, utility_bill_id, auditor_id, is_late_receive, is_late_payment, is_overdue_more_than_2_months, is_disbursement_over_2_months, is_wrong_month, is_phone_over_limit, is_phone_usage_over_limit, is_wrong_budget, is_duplicate, is_anomaly_expense, is_manual_anomaly, status, remarks, manual_anomaly_reason, attachment_proof, created_at, updated_at
`

type FlagManualAnomalyParams struct {
	ID                  string      `json:"id"`
	UtilityBillID       string      `json:"utility_bill_id"`
	AuditorID           string      `json:"auditor_id"`
	ManualAnomalyReason pgtype.Text `json:"manual_anomaly_reason"`
}

func (q *Queries) FlagManualAnomaly(ctx context.Context, arg FlagManualAnomalyParams) (Audit, error) {
	row := q.db.QueryRow(ctx, flagManualAnomaly,
		arg.ID,
		arg.UtilityBillID,
		arg.AuditorID,
		arg.ManualAnomalyReason,
	)
	var i Audit
	err := row.Scan(
		&i.ID,
		&i.UtilityBillID,
		&i.AuditorID,
		&i.IsLateReceive,
		&i.IsLatePayment,
		&i.IsOverdueMoreThan2Months,
		&i.IsDisbursementOver2Months,
		&i.IsWrongMonth,
		&i.IsPhoneOverLimit,
		&i.IsPhoneUsageOverLimit,
		&i.IsWrongBudget,
		&i.IsDuplicate,
		&i.IsAnomalyExpense,
		&i.IsManualAnomaly,
		&i.Status,
		&i.Remarks,
		&i.ManualAnomalyReason,
		&i.AttachmentProof,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAuditByBillID = `-- name: GetAuditByBillID :one
SELECT id, utility_bill_id, auditor_id, is_late_receive, is_late_payment, is_overdue_more_than_2_months, is_disbursement_over_2_months, is_wrong_month, is_phone_over_limit, is_phone_usage_over_limit, is_wrong_budget, is_duplicate, is_anomaly_expense, is_manual_anomaly, status, remarks, manual_anomaly_reason, attachment_proof, created_at, updated_at FROM audits
WHERE utility_bill_id = $1 LIMIT 1
`

func (q *Queries) GetAuditByBillID(ctx context.Context, utilityBillID string) (Audit, error) {
	row := q.db.QueryRow(ctx, getAuditByBillID, utilityBillID)
	var i Audit
	err := row.Scan(
		&i.ID,
		&i.UtilityBillID,
		&i.AuditorID,
		&i.IsLateReceive,
		&i.IsLatePayment,
		&i.IsOverdueMoreThan2Months,
		&i.IsDisbursementOver2Months,
		&i.IsWrongMonth,
		&i.IsPhoneOverLimit,
		&i.IsPhoneUsageOverLimit,
		&i.IsWrongBudget,
		&i.IsDuplicate,
		&i.IsAnomalyExpense,
		&i.IsManualAnomaly,
		&i.Status,
		&i.Remarks,
		&i.ManualAnomalyReason,
		&i.AttachmentProof,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAudits = `-- name: ListAudits :many
SELECT a.id, a.utility_bill_id, a.auditor_id, a.is_late_receive, a.is_late_payment, a.is_overdue_more_than_2_months, a.is_disbursement_over_2_months, a.is_wrong_month, a.is_phone_over_limit, a.is_phone_usage_over_limit, a.is_wrong_budget, a.is_duplicate, a.is_anomaly_expense, a.is_manual_anomaly, a.status, a.remarks, a.manual_anomaly_reason, a.attachment_proof, a.created_at, a.updated_at, 
       b.bill_code, b.utility_type, b.invoice_amount, b.billing_month, b.billing_year,
       d.full_name AS department_name
FROM audits a
JOIN utility_bills b ON a.utility_bill_id = b.id
JOIN departments d ON b.department_id = d.id
WHERE ($1::text IS NULL OR a.status = $1)
ORDER BY a.created_at DESC
`

type ListAuditsRow struct {
	ID                        string             `json:"id"`
	UtilityBillID             string             `json:"utility_bill_id"`
	AuditorID                 string             `json:"auditor_id"`
	IsLateReceive             pgtype.Bool        `json:"is_late_receive"`
	IsLatePayment             pgtype.Bool        `json:"is_late_payment"`
	IsOverdueMoreThan2Months  pgtype.Bool        `json:"is_overdue_more_than_2_months"`
	IsDisbursementOver2Months pgtype.Bool        `json:"is_disbursement_over_2_months"`
	IsWrongMonth              pgtype.Bool        `json:"is_wrong_month"`
	IsPhoneOverLimit          pgtype.Bool        `json:"is_phone_over_limit"`
	IsPhoneUsageOverLimit     pgtype.Bool        `json:"is_phone_usage_over_limit"`
	IsWrongBudget             pgtype.Bool        `json:"is_wrong_budget"`
	IsDuplicate               pgtype.Bool        `json:"is_duplicate"`
	IsAnomalyExpense          pgtype.Bool        `json:"is_anomaly_expense"`
	IsManualAnomaly           pgtype.Bool        `json:"is_manual_anomaly"`
	Status                    string             `json:"status"`
	Remarks                   pgtype.Text        `json:"remarks"`
	ManualAnomalyReason       pgtype.Text        `json:"manual_anomaly_reason"`
	AttachmentProof           pgtype.Text        `json:"attachment_proof"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	BillCode                  pgtype.Text        `json:"bill_code"`
	UtilityType               string             `json:"utility_type"`
	InvoiceAmount             pgtype.Numeric     `json:"invoice_amount"`
	BillingMonth              int32              `json:"billing_month"`
	BillingYear               int32              `json:"billing_year"`
	DepartmentName            string             `json:"department_name"`
}

func (q *Queries) ListAudits(ctx context.Context, status pgtype.Text) ([]ListAuditsRow, error) {
	rows, err := q.db.Query(ctx, listAudits, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditsRow
	for rows.Next() {
		var i ListAuditsRow
		if err := rows.Scan(
			&i.ID,
			&i.UtilityBillID,
			&i.AuditorID,
			&i.IsLateReceive,
			&i.IsLatePayment,
			&i.IsOverdueMoreThan2Months,
			&i.IsDisbursementOver2Months,
			&i.IsWrongMonth,
			&i.IsPhoneOverLimit,
			&i.IsPhoneUsageOverLimit,
			&i.IsWrongBudget,
			&i.IsDuplicate,
			&i.IsAnomalyExpense,
			&i.IsManualAnomaly,
			&i.Status,
			&i.Remarks,
			&i.ManualAnomalyReason,
			&i.AttachmentProof,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BillCode,
			&i.UtilityType,
			&i.InvoiceAmount,
			&i.BillingMonth,
			&i.BillingYear,
			&i.DepartmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveAudit = `-- name: ResolveAudit :one
UPDATE audits
SET 
    status = 'CORRECTED',
    remarks = $2,
    attachment_proof = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, utility_bill_id, auditor_id, is_late_receive, is_late_payment, is_overdue_more_than_2_months, is_disbursement_over_2_months, is_wrong_month, is_phone_over_limit, is_phone_usage_over_limit, is_wrong_budget, is_duplicate, is_anomaly_expense, is_manual_anomaly, status, remarks, manual_anomaly_reason, attachment_proof, created_at, updated_at
`

type ResolveAuditParams struct {
	ID              string      `json:"id"`
	Remarks         pgtype.Text `json:"remarks"`
	AttachmentProof pgtype.Text `json:"attachment_proof"`
}

func (q *Queries) ResolveAudit(ctx context.Context, arg ResolveAuditParams) (Audit, error) {
	row := q.db.QueryRow(ctx, resolveAudit, arg.ID, arg.Remarks, arg.AttachmentProof)
	var i Audit
	err := row.Scan(
		&i.ID,
		&i.UtilityBillID,
		&i.AuditorID,
		&i.IsLateReceive,
		&i.IsLatePayment,
		&i.IsOverdueMoreThan2Months,
		&i.IsDisbursementOver2Months,
		&i.IsWrongMonth,
		&i.IsPhoneOverLimit,
		&i.IsPhoneUsageOverLimit,
		&i.IsWrongBudget,
		&i.IsDuplicate,
		&i.IsAnomalyExpense,
		&i.IsManualAnomaly,
		&i.Status,
		&i.Remarks,
		&i.ManualAnomalyReason,
		&i.AttachmentProof,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unflagManualAnomaly = `-- name: UnflagManualAnomaly :one
UPDATE audits
SET 
    is_manual_anomaly = false,
    manual_anomaly_reason = NULL,
    updated_at = NOW()
WHERE utility_bill_id = $1
RETURNING id, utility_bill_id, auditor_id, is_late_receive, is_late_payment, is_overdue_more_than_2_months, is_disbursement_over_2_months, is_wrong_month, is_phone_over_limit, is_phone_usage_over_limit, is_wrong_budget, is_duplicate, is_anomaly_expense, is_manual_anomaly, status, remarks, manual_anomaly_reason, attachment_proof, created_at, updated_at
`

func (q *Queries) UnflagManualAnomaly(ctx context.Context, utilityBillID string) (Audit, error) {
	row := q.db.QueryRow(ctx, unflagManualAnomaly, utilityBillID)
	var i Audit
	err := row.Scan(
		&i.ID,
		&i.UtilityBillID,
		&i.AuditorID,
		&i.IsLateReceive,
		&i.IsLatePayment,
		&i.IsOverdueMoreThan2Months,
		&i.IsDisbursementOver2Months,
		&i.IsWrongMonth,
		&i.IsPhoneOverLimit,
		&i.IsPhoneUsageOverLimit,
		&i.IsWrongBudget,
		&i.IsDuplicate,
		&i.IsAnomalyExpense,
		&i.IsManualAnomaly,
		&i.Status,
		&i.Remarks,
		&i.ManualAnomalyReason,
		&i.AttachmentProof,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertAudit = `-- name: UpsertAudit :one
INSERT INTO audits (
    id, utility_bill_id, auditor_id,
    is_late_receive, is_late_payment, is_overdue_more_than_2_months,
    is_disbursement_over_2_months, is_wrong_month, is_phone_over_limit,
    is_phone_usage_over_limit, is_wrong_budget, is_duplicate,
    is_anomaly_expense, is_manual_anomaly, status, remarks,
    manual_anomaly_reason, attachment_proof, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18, NOW(), NOW()
)
ON CONFLICT (id) DO UPDATE
SET 
    is_late_receive = EXCLUDED.is_late_receive,
    is_late_payment = EXCLUDED.is_late_payment,
    is_overdue_more_than_2_months = EXCLUDED.is_overdue_more_than_2_months,
    is_disbursement_over_2_months = EXCLUDED.is_disbursement_over_2_months,
    is_wrong_month = EXCLUDED.is_wrong_month,
    is_phone_over_limit = EXCLUDED.is_phone_over_limit,
    is_phone_usage_over_limit = EXCLUDED.is_phone_usage_over_limit,
    is_wrong_budget = EXCLUDED.is_wrong_budget,
    is_duplicate = EXCLUDED.is_duplicate,
    is_anomaly_expense = EXCLUDED.is_anomaly_expense,
    is_manual_anomaly = EXCLUDED.is_manual_anomaly,
    status = EXCLUDED.status,
    remarks = EXCLUDED.remarks,
    manual_anomaly_reason = EXCLUDED.manual_anomaly_reason,
    attachment_proof = EXCLUDED.attachment_proof,
    updated_at = NOW()
RETURNING id, utility_bill_id, auditor_id, is_late_receive, is_late_payment, is_overdue_more_than_2_months, is_disbursement_over_2_months, is_wrong_month, is_phone_over_limit, is_phone_usage_over_limit, is_wrong_budget, is_duplicate, is_anomaly_expense, is_manual_anomaly, status, remarks, manual_anomaly_reason, attachment_proof, created_at, updated_at
`

type UpsertAuditParams struct {
	ID                        string      `json:"id"`
	UtilityBillID             string      `json:"utility_bill_id"`
	AuditorID                 string      `json:"auditor_id"`
	IsLateReceive             pgtype.Bool `json:"is_late_receive"`
	IsLatePayment             pgtype.Bool `json:"is_late_payment"`
	IsOverdueMoreThan2Months  pgtype.Bool `json:"is_overdue_more_than_2_months"`
	IsDisbursementOver2Months pgtype.Bool `json:"is_disbursement_over_2_months"`
	IsWrongMonth              pgtype.Bool `json:"is_wrong_month"`
	IsPhoneOverLimit          pgtype.Bool `json:"is_phone_over_limit"`
	IsPhoneUsageOverLimit     pgtype.Bool `json:"is_phone_usage_over_limit"`
	IsWrongBudget             pgtype.Bool `json:"is_wrong_budget"`
	IsDuplicate               pgtype.Bool `json:"is_duplicate"`
	IsAnomalyExpense          pgtype.Bool `json:"is_anomaly_expense"`
	IsManualAnomaly           pgtype.Bool `json:"is_manual_anomaly"`
	Status                    string      `json:"status"`
	Remarks                   pgtype.Text `json:"remarks"`
	ManualAnomalyReason       pgtype.Text `json:"manual_anomaly_reason"`
	AttachmentProof           pgtype.Text `json:"attachment_proof"`
}

func (q *Queries) UpsertAudit(ctx context.Context, arg UpsertAuditParams) (Audit, error) {
	row := q.db.QueryRow(ctx, upsertAudit,
		arg.ID,
		arg.UtilityBillID,
		arg.AuditorID,
		arg.IsLateReceive,
		arg.IsLatePayment,
		arg.IsOverdueMoreThan2Months,
		arg.IsDisbursementOver2Months,
		arg.IsWrongMonth,
		arg.IsPhoneOverLimit,
		arg.IsPhoneUsageOverLimit,
		arg.IsWrongBudget,
		arg.IsDuplicate,
		arg.IsAnomalyExpense,
		arg.IsManualAnomaly,
		arg.Status,
		arg.Remarks,
		arg.ManualAnomalyReason,
		arg.AttachmentProof,
	)
	var i Audit
	err := row.Scan(
		&i.ID,
		&i.UtilityBillID,
		&i.AuditorID,
		&i.IsLateReceive,
		&i.IsLatePayment,
		&i.IsOverdueMoreThan2Months,
		&i.IsDisbursementOver2Months,
		&i.IsWrongMonth,
		&i.IsPhoneOverLimit,
		&i.IsPhoneUsageOverLimit,
		&i.IsWrongBudget,
		&i.IsDuplicate,
		&i.IsAnomalyExpense,
		&i.IsManualAnomaly,
		&i.Status,
		&i.Remarks,
		&i.ManualAnomalyReason,
		&i.AttachmentProof,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
