// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bills.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBill = `-- name: CreateBill :one
INSERT INTO utility_bills (
    id, bill_code, department_id, utility_type, billing_month, billing_year,
    provider, service_number, service_breakdown, invoice_number, invoice_date,
    location_type, usage_amount, invoice_amount, estimated_amount,
    received_date, sent_to_disbursing_date, disbursing_received_date,
    payment_date, payment_doc_number, doc_type, account_code, budget_code,
    fund_source, paid_amount, payment_status, invoice_status,
    receipt_number, receipt_date, receipt_payment_date,
    attachment_invoice, attachment_receipt, attachment_payment_doc,
    attachment_direct_payment, attachment_ktb_report,
    is_pending_bill_only, deposit_unit_id,
    created_by, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15,
    $16, $17, $18, $19, $20, $21, $22, $23, $24, $25, $26, $27,
    $28, $29, $30, $31, $32, $33, $34, $35, $36, $37, $38, NOW(), NOW()
)
RETURNING id, bill_code, department_id, utility_type, billing_month, billing_year, provider, service_number, service_breakdown, invoice_number, invoice_date, location_type, usage_amount, invoice_amount, estimated_amount, received_date, sent_to_disbursing_date, disbursing_received_date, payment_date, payment_doc_number, doc_type, account_code, budget_code, fund_source, paid_amount, payment_status, invoice_status, receipt_number, receipt_date, receipt_payment_date, attachment_invoice, attachment_receipt, attachment_payment_doc, attachment_direct_payment, attachment_ktb_report, is_pending_bill_only, deposit_unit_id, is_reviewed, reviewed_by, reviewed_at, created_by, created_at, updated_at
`

type CreateBillParams struct {
	ID                      string             `json:"id"`
	BillCode                pgtype.Text        `json:"bill_code"`
	DepartmentID            string             `json:"department_id"`
	UtilityType             string             `json:"utility_type"`
	BillingMonth            int32              `json:"billing_month"`
	BillingYear             int32              `json:"billing_year"`
	Provider                pgtype.Text        `json:"provider"`
	ServiceNumber           pgtype.Text        `json:"service_number"`
	ServiceBreakdown        pgtype.Text        `json:"service_breakdown"`
	InvoiceNumber           pgtype.Text        `json:"invoice_number"`
	InvoiceDate             pgtype.Timestamptz `json:"invoice_date"`
	LocationType            pgtype.Text        `json:"location_type"`
	UsageAmount             pgtype.Numeric     `json:"usage_amount"`
	InvoiceAmount           pgtype.Numeric     `json:"invoice_amount"`
	EstimatedAmount         pgtype.Numeric     `json:"estimated_amount"`
	ReceivedDate            pgtype.Timestamptz `json:"received_date"`
	SentToDisbursingDate    pgtype.Timestamptz `json:"sent_to_disbursing_date"`
	DisbursingReceivedDate  pgtype.Timestamptz `json:"disbursing_received_date"`
	PaymentDate             pgtype.Timestamptz `json:"payment_date"`
	PaymentDocNumber        pgtype.Text        `json:"payment_doc_number"`
	DocType                 pgtype.Text        `json:"doc_type"`
	AccountCode             pgtype.Text        `json:"account_code"`
	BudgetCode              pgtype.Text        `json:"budget_code"`
	FundSource              pgtype.Text        `json:"fund_source"`
	PaidAmount              pgtype.Numeric     `json:"paid_amount"`
	PaymentStatus           string             `json:"payment_status"`
	InvoiceStatus           string             `json:"invoice_status"`
	ReceiptNumber           pgtype.Text        `json:"receipt_number"`
	ReceiptDate             pgtype.Timestamptz `json:"receipt_date"`
	ReceiptPaymentDate      pgtype.Timestamptz `json:"receipt_payment_date"`
	AttachmentInvoice       pgtype.Text        `json:"attachment_invoice"`
	AttachmentReceipt       pgtype.Text        `json:"attachment_receipt"`
	AttachmentPaymentDoc    pgtype.Text        `json:"attachment_payment_doc"`
	AttachmentDirectPayment pgtype.Text        `json:"attachment_direct_payment"`
	AttachmentKtbReport     pgtype.Text        `json:"attachment_ktb_report"`
	IsPendingBillOnly       bool               `json:"is_pending_bill_only"`
	DepositUnitID           pgtype.Text        `json:"deposit_unit_id"`
	CreatedBy               string             `json:"created_by"`
}

func (q *Queries) CreateBill(ctx context.Context, arg CreateBillParams) (UtilityBill, error) {
	row := q.db.QueryRow(ctx, createBill,
		arg.ID,
		arg.BillCode,
		arg.DepartmentID,
		arg.UtilityType,
		arg.BillingMonth,
		arg.BillingYear,
		arg.Provider,
		arg.ServiceNumber,
		arg.ServiceBreakdown,
		arg.InvoiceNumber,
		arg.InvoiceDate,
		arg.LocationType,
		arg.UsageAmount,
		arg.InvoiceAmount,
		arg.EstimatedAmount,
		arg.ReceivedDate,
		arg.SentToDisbursingDate,
		arg.DisbursingReceivedDate,
		arg.PaymentDate,
		arg.PaymentDocNumber,
		arg.DocType,
		arg.AccountCode,
		arg.BudgetCode,
		arg.FundSource,
		arg.PaidAmount,
		arg.PaymentStatus,
		arg.InvoiceStatus,
		arg.ReceiptNumber,
		arg.ReceiptDate,
		arg.ReceiptPaymentDate,
		arg.AttachmentInvoice,
		arg.AttachmentReceipt,
		arg.AttachmentPaymentDoc,
		arg.AttachmentDirectPayment,
		arg.AttachmentKtbReport,
		arg.IsPendingBillOnly,
		arg.DepositUnitID,
		arg.CreatedBy,
	)
	var i UtilityBill
	err := row.Scan(
		&i.ID,
		&i.BillCode,
		&i.DepartmentID,
		&i.UtilityType,
		&i.BillingMonth,
		&i.BillingYear,
		&i.Provider,
		&i.ServiceNumber,
		&i.ServiceBreakdown,
		&i.InvoiceNumber,
		&i.InvoiceDate,
		&i.LocationType,
		&i.UsageAmount,
		&i.InvoiceAmount,
		&i.EstimatedAmount,
		&i.ReceivedDate,
		&i.SentToDisbursingDate,
		&i.DisbursingReceivedDate,
		&i.PaymentDate,
		&i.PaymentDocNumber,
		&i.DocType,
		&i.AccountCode,
		&i.BudgetCode,
		&i.FundSource,
		&i.PaidAmount,
		&i.PaymentStatus,
		&i.InvoiceStatus,
		&i.ReceiptNumber,
		&i.ReceiptDate,
		&i.ReceiptPaymentDate,
		&i.AttachmentInvoice,
		&i.AttachmentReceipt,
		&i.AttachmentPaymentDoc,
		&i.AttachmentDirectPayment,
		&i.AttachmentKtbReport,
		&i.IsPendingBillOnly,
		&i.DepositUnitID,
		&i.IsReviewed,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBillActivityLog = `-- name: CreateBillActivityLog :one
INSERT INTO bill_activity_logs (
    id, bill_id, user_id, action, details, created_at
) VALUES (
    $1, $2, $3, $4, $5, NOW()
)
RETURNING id, bill_id, user_id, action, details, created_at
`

type CreateBillActivityLogParams struct {
	ID      string      `json:"id"`
	BillID  string      `json:"bill_id"`
	UserID  string      `json:"user_id"`
	Action  string      `json:"action"`
	Details pgtype.Text `json:"details"`
}

func (q *Queries) CreateBillActivityLog(ctx context.Context, arg CreateBillActivityLogParams) (BillActivityLog, error) {
	row := q.db.QueryRow(ctx, createBillActivityLog,
		arg.ID,
		arg.BillID,
		arg.UserID,
		arg.Action,
		arg.Details,
	)
	var i BillActivityLog
	err := row.Scan(
		&i.ID,
		&i.BillID,
		&i.UserID,
		&i.Action,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBill = `-- name: DeleteBill :exec
DELETE FROM utility_bills
WHERE id = $1
`

func (q *Queries) DeleteBill(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteBill, id)
	return err
}

const getBillActivityLogs = `-- name: GetBillActivityLogs :many
SELECT l.id, l.bill_id, l.user_id, l.action, l.details, l.created_at, u.name AS user_name, u.email AS user_email
FROM bill_activity_logs l
LEFT JOIN users u ON l.user_id = u.id
WHERE l.bill_id = $1
ORDER BY l.created_at DESC
`

type GetBillActivityLogsRow struct {
	ID        string             `json:"id"`
	BillID    string             `json:"bill_id"`
	UserID    string             `json:"user_id"`
	Action    string             `json:"action"`
	Details   pgtype.Text        `json:"details"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UserName  pgtype.Text        `json:"user_name"`
	UserEmail pgtype.Text        `json:"user_email"`
}

func (q *Queries) GetBillActivityLogs(ctx context.Context, billID string) ([]GetBillActivityLogsRow, error) {
	rows, err := q.db.Query(ctx, getBillActivityLogs, billID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBillActivityLogsRow
	for rows.Next() {
		var i GetBillActivityLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.BillID,
			&i.UserID,
			&i.Action,
			&i.Details,
			&i.CreatedAt,
			&i.UserName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBillByID = `-- name: GetBillByID :one
SELECT b.id, b.bill_code, b.department_id, b.utility_type, b.billing_month, b.billing_year, b.provider, b.service_number, b.service_breakdown, b.invoice_number, b.invoice_date, b.location_type, b.usage_amount, b.invoice_amount, b.estimated_amount, b.received_date, b.sent_to_disbursing_date, b.disbursing_received_date, b.payment_date, b.payment_doc_number, b.doc_type, b.account_code, b.budget_code, b.fund_source, b.paid_amount, b.payment_status, b.invoice_status, b.receipt_number, b.receipt_date, b.receipt_payment_date, b.attachment_invoice, b.attachment_receipt, b.attachment_payment_doc, b.attachment_direct_payment, b.attachment_ktb_report, b.is_pending_bill_only, b.deposit_unit_id, b.is_reviewed, b.reviewed_by, b.reviewed_at, b.created_by, b.created_at, b.updated_at, 
       d.full_name AS department_name, 
       d.short_name AS department_short_name,
       d.cost_center_code AS department_cost_center,
       dep_unit.full_name AS deposit_unit_name,
       a.id AS audit_id,
       a.status AS audit_status,
       a.is_late_receive,
       a.is_late_payment,
       a.is_overdue_more_than_2_months,
       a.is_disbursement_over_2_months,
       a.is_wrong_month,
       a.is_phone_over_limit,
       a.is_phone_usage_over_limit,
       a.is_wrong_budget,
       a.is_duplicate,
       a.is_anomaly_expense,
       a.is_manual_anomaly,
       a.manual_anomaly_reason
FROM utility_bills b
LEFT JOIN departments d ON b.department_id = d.id
LEFT JOIN departments dep_unit ON b.deposit_unit_id = dep_unit.id
LEFT JOIN audits a ON b.id = a.utility_bill_id
WHERE b.id = $1 LIMIT 1
`

type GetBillByIDRow struct {
	ID                        string             `json:"id"`
	BillCode                  pgtype.Text        `json:"bill_code"`
	DepartmentID              string             `json:"department_id"`
	UtilityType               string             `json:"utility_type"`
	BillingMonth              int32              `json:"billing_month"`
	BillingYear               int32              `json:"billing_year"`
	Provider                  pgtype.Text        `json:"provider"`
	ServiceNumber             pgtype.Text        `json:"service_number"`
	ServiceBreakdown          pgtype.Text        `json:"service_breakdown"`
	InvoiceNumber             pgtype.Text        `json:"invoice_number"`
	InvoiceDate               pgtype.Timestamptz `json:"invoice_date"`
	LocationType              pgtype.Text        `json:"location_type"`
	UsageAmount               pgtype.Numeric     `json:"usage_amount"`
	InvoiceAmount             pgtype.Numeric     `json:"invoice_amount"`
	EstimatedAmount           pgtype.Numeric     `json:"estimated_amount"`
	ReceivedDate              pgtype.Timestamptz `json:"received_date"`
	SentToDisbursingDate      pgtype.Timestamptz `json:"sent_to_disbursing_date"`
	DisbursingReceivedDate    pgtype.Timestamptz `json:"disbursing_received_date"`
	PaymentDate               pgtype.Timestamptz `json:"payment_date"`
	PaymentDocNumber          pgtype.Text        `json:"payment_doc_number"`
	DocType                   pgtype.Text        `json:"doc_type"`
	AccountCode               pgtype.Text        `json:"account_code"`
	BudgetCode                pgtype.Text        `json:"budget_code"`
	FundSource                pgtype.Text        `json:"fund_source"`
	PaidAmount                pgtype.Numeric     `json:"paid_amount"`
	PaymentStatus             string             `json:"payment_status"`
	InvoiceStatus             string             `json:"invoice_status"`
	ReceiptNumber             pgtype.Text        `json:"receipt_number"`
	ReceiptDate               pgtype.Timestamptz `json:"receipt_date"`
	ReceiptPaymentDate        pgtype.Timestamptz `json:"receipt_payment_date"`
	AttachmentInvoice         pgtype.Text        `json:"attachment_invoice"`
	AttachmentReceipt         pgtype.Text        `json:"attachment_receipt"`
	AttachmentPaymentDoc      pgtype.Text        `json:"attachment_payment_doc"`
	AttachmentDirectPayment   pgtype.Text        `json:"attachment_direct_payment"`
	AttachmentKtbReport       pgtype.Text        `json:"attachment_ktb_report"`
	IsPendingBillOnly         bool               `json:"is_pending_bill_only"`
	DepositUnitID             pgtype.Text        `json:"deposit_unit_id"`
	IsReviewed                pgtype.Bool        `json:"is_reviewed"`
	ReviewedBy                pgtype.Text        `json:"reviewed_by"`
	ReviewedAt                pgtype.Timestamptz `json:"reviewed_at"`
	CreatedBy                 string             `json:"created_by"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	DepartmentName            pgtype.Text        `json:"department_name"`
	DepartmentShortName       pgtype.Text        `json:"department_short_name"`
	DepartmentCostCenter      pgtype.Text        `json:"department_cost_center"`
	DepositUnitName           pgtype.Text        `json:"deposit_unit_name"`
	AuditID                   pgtype.Text        `json:"audit_id"`
	AuditStatus               pgtype.Text        `json:"audit_status"`
	IsLateReceive             pgtype.Bool        `json:"is_late_receive"`
	IsLatePayment             pgtype.Bool        `json:"is_late_payment"`
	IsOverdueMoreThan2Months  pgtype.Bool        `json:"is_overdue_more_than_2_months"`
	IsDisbursementOver2Months pgtype.Bool        `json:"is_disbursement_over_2_months"`
	IsWrongMonth              pgtype.Bool        `json:"is_wrong_month"`
	IsPhoneOverLimit          pgtype.Bool        `json:"is_phone_over_limit"`
	IsPhoneUsageOverLimit     pgtype.Bool        `json:"is_phone_usage_over_limit"`
	IsWrongBudget             pgtype.Bool        `json:"is_wrong_budget"`
	IsDuplicate               pgtype.Bool        `json:"is_duplicate"`
	IsAnomalyExpense          pgtype.Bool        `json:"is_anomaly_expense"`
	IsManualAnomaly           pgtype.Bool        `json:"is_manual_anomaly"`
	ManualAnomalyReason       pgtype.Text        `json:"manual_anomaly_reason"`
}

func (q *Queries) GetBillByID(ctx context.Context, id string) (GetBillByIDRow, error) {
	row := q.db.QueryRow(ctx, getBillByID, id)
	var i GetBillByIDRow
	err := row.Scan(
		&i.ID,
		&i.BillCode,
		&i.DepartmentID,
		&i.UtilityType,
		&i.BillingMonth,
		&i.BillingYear,
		&i.Provider,
		&i.ServiceNumber,
		&i.ServiceBreakdown,
		&i.InvoiceNumber,
		&i.InvoiceDate,
		&i.LocationType,
		&i.UsageAmount,
		&i.InvoiceAmount,
		&i.EstimatedAmount,
		&i.ReceivedDate,
		&i.SentToDisbursingDate,
		&i.DisbursingReceivedDate,
		&i.PaymentDate,
		&i.PaymentDocNumber,
		&i.DocType,
		&i.AccountCode,
		&i.BudgetCode,
		&i.FundSource,
		&i.PaidAmount,
		&i.PaymentStatus,
		&i.InvoiceStatus,
		&i.ReceiptNumber,
		&i.ReceiptDate,
		&i.ReceiptPaymentDate,
		&i.AttachmentInvoice,
		&i.AttachmentReceipt,
		&i.AttachmentPaymentDoc,
		&i.AttachmentDirectPayment,
		&i.AttachmentKtbReport,
		&i.IsPendingBillOnly,
		&i.DepositUnitID,
		&i.IsReviewed,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DepartmentName,
		&i.DepartmentShortName,
		&i.DepartmentCostCenter,
		&i.DepositUnitName,
		&i.AuditID,
		&i.AuditStatus,
		&i.IsLateReceive,
		&i.IsLatePayment,
		&i.IsOverdueMoreThan2Months,
		&i.IsDisbursementOver2Months,
		&i.IsWrongMonth,
		&i.IsPhoneOverLimit,
		&i.IsPhoneUsageOverLimit,
		&i.IsWrongBudget,
		&i.IsDuplicate,
		&i.IsAnomalyExpense,
		&i.IsManualAnomaly,
		&i.ManualAnomalyReason,
	)
	return i, err
}

const getLatestBillCodeForPrefix = `-- name: GetLatestBillCodeForPrefix :one
SELECT bill_code FROM utility_bills
WHERE bill_code LIKE $1
ORDER BY bill_code DESC
LIMIT 1
`

func (q *Queries) GetLatestBillCodeForPrefix(ctx context.Context, billCode pgtype.Text) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getLatestBillCodeForPrefix, billCode)
	var bill_code pgtype.Text
	err := row.Scan(&bill_code)
	return bill_code, err
}

const listBills = `-- name: ListBills :many
SELECT b.id, b.bill_code, b.department_id, b.utility_type, b.billing_month, b.billing_year, b.provider, b.service_number, b.service_breakdown, b.invoice_number, b.invoice_date, b.location_type, b.usage_amount, b.invoice_amount, b.estimated_amount, b.received_date, b.sent_to_disbursing_date, b.disbursing_received_date, b.payment_date, b.payment_doc_number, b.doc_type, b.account_code, b.budget_code, b.fund_source, b.paid_amount, b.payment_status, b.invoice_status, b.receipt_number, b.receipt_date, b.receipt_payment_date, b.attachment_invoice, b.attachment_receipt, b.attachment_payment_doc, b.attachment_direct_payment, b.attachment_ktb_report, b.is_pending_bill_only, b.deposit_unit_id, b.is_reviewed, b.reviewed_by, b.reviewed_at, b.created_by, b.created_at, b.updated_at, 
       d.full_name AS department_name, 
       d.short_name AS department_short_name,
       d.cost_center_code AS department_cost_center,
       dep_unit.full_name AS deposit_unit_name,
       a.id AS audit_id,
       a.status AS audit_status,
       a.is_late_receive,
       a.is_late_payment,
       a.is_overdue_more_than_2_months,
       a.is_disbursement_over_2_months,
       a.is_wrong_month,
       a.is_phone_over_limit,
       a.is_phone_usage_over_limit,
       a.is_wrong_budget,
       a.is_duplicate,
       a.is_anomaly_expense,
       a.is_manual_anomaly,
       a.manual_anomaly_reason
FROM utility_bills b
LEFT JOIN departments d ON b.department_id = d.id
LEFT JOIN departments dep_unit ON b.deposit_unit_id = dep_unit.id
LEFT JOIN audits a ON b.id = a.utility_bill_id
WHERE 
    ($1::text IS NULL OR b.department_id = $1)
    AND ($2::text IS NULL OR b.utility_type = $2)
    AND ($3::int IS NULL OR b.billing_year = $3)
    AND ($4::int IS NULL OR b.billing_month = $4)
    AND ($5::text IS NULL OR b.payment_status = $5)
ORDER BY b.created_at DESC
LIMIT 500
`

type ListBillsParams struct {
	DepartmentID  pgtype.Text `json:"department_id"`
	UtilityType   pgtype.Text `json:"utility_type"`
	BillingYear   pgtype.Int4 `json:"billing_year"`
	BillingMonth  pgtype.Int4 `json:"billing_month"`
	PaymentStatus pgtype.Text `json:"payment_status"`
}

type ListBillsRow struct {
	ID                        string             `json:"id"`
	BillCode                  pgtype.Text        `json:"bill_code"`
	DepartmentID              string             `json:"department_id"`
	UtilityType               string             `json:"utility_type"`
	BillingMonth              int32              `json:"billing_month"`
	BillingYear               int32              `json:"billing_year"`
	Provider                  pgtype.Text        `json:"provider"`
	ServiceNumber             pgtype.Text        `json:"service_number"`
	ServiceBreakdown          pgtype.Text        `json:"service_breakdown"`
	InvoiceNumber             pgtype.Text        `json:"invoice_number"`
	InvoiceDate               pgtype.Timestamptz `json:"invoice_date"`
	LocationType              pgtype.Text        `json:"location_type"`
	UsageAmount               pgtype.Numeric     `json:"usage_amount"`
	InvoiceAmount             pgtype.Numeric     `json:"invoice_amount"`
	EstimatedAmount           pgtype.Numeric     `json:"estimated_amount"`
	ReceivedDate              pgtype.Timestamptz `json:"received_date"`
	SentToDisbursingDate      pgtype.Timestamptz `json:"sent_to_disbursing_date"`
	DisbursingReceivedDate    pgtype.Timestamptz `json:"disbursing_received_date"`
	PaymentDate               pgtype.Timestamptz `json:"payment_date"`
	PaymentDocNumber          pgtype.Text        `json:"payment_doc_number"`
	DocType                   pgtype.Text        `json:"doc_type"`
	AccountCode               pgtype.Text        `json:"account_code"`
	BudgetCode                pgtype.Text        `json:"budget_code"`
	FundSource                pgtype.Text        `json:"fund_source"`
	PaidAmount                pgtype.Numeric     `json:"paid_amount"`
	PaymentStatus             string             `json:"payment_status"`
	InvoiceStatus             string             `json:"invoice_status"`
	ReceiptNumber             pgtype.Text        `json:"receipt_number"`
	ReceiptDate               pgtype.Timestamptz `json:"receipt_date"`
	ReceiptPaymentDate        pgtype.Timestamptz `json:"receipt_payment_date"`
	AttachmentInvoice         pgtype.Text        `json:"attachment_invoice"`
	AttachmentReceipt         pgtype.Text        `json:"attachment_receipt"`
	AttachmentPaymentDoc      pgtype.Text        `json:"attachment_payment_doc"`
	AttachmentDirectPayment   pgtype.Text        `json:"attachment_direct_payment"`
	AttachmentKtbReport       pgtype.Text        `json:"attachment_ktb_report"`
	IsPendingBillOnly         bool               `json:"is_pending_bill_only"`
	DepositUnitID             pgtype.Text        `json:"deposit_unit_id"`
	IsReviewed                pgtype.Bool        `json:"is_reviewed"`
	ReviewedBy                pgtype.Text        `json:"reviewed_by"`
	ReviewedAt                pgtype.Timestamptz `json:"reviewed_at"`
	CreatedBy                 string             `json:"created_by"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
	DepartmentName            pgtype.Text        `json:"department_name"`
	DepartmentShortName       pgtype.Text        `json:"department_short_name"`
	DepartmentCostCenter      pgtype.Text        `json:"department_cost_center"`
	DepositUnitName           pgtype.Text        `json:"deposit_unit_name"`
	AuditID                   pgtype.Text        `json:"audit_id"`
	AuditStatus               pgtype.Text        `json:"audit_status"`
	IsLateReceive             pgtype.Bool        `json:"is_late_receive"`
	IsLatePayment             pgtype.Bool        `json:"is_late_payment"`
	IsOverdueMoreThan2Months  pgtype.Bool        `json:"is_overdue_more_than_2_months"`
	IsDisbursementOver2Months pgtype.Bool        `json:"is_disbursement_over_2_months"`
	IsWrongMonth              pgtype.Bool        `json:"is_wrong_month"`
	IsPhoneOverLimit          pgtype.Bool        `json:"is_phone_over_limit"`
	IsPhoneUsageOverLimit     pgtype.Bool        `json:"is_phone_usage_over_limit"`
	IsWrongBudget             pgtype.Bool        `json:"is_wrong_budget"`
	IsDuplicate               pgtype.Bool        `json:"is_duplicate"`
	IsAnomalyExpense          pgtype.Bool        `json:"is_anomaly_expense"`
	IsManualAnomaly           pgtype.Bool        `json:"is_manual_anomaly"`
	ManualAnomalyReason       pgtype.Text        `json:"manual_anomaly_reason"`
}

func (q *Queries) ListBills(ctx context.Context, arg ListBillsParams) ([]ListBillsRow, error) {
	rows, err := q.db.Query(ctx, listBills,
		arg.DepartmentID,
		arg.UtilityType,
		arg.BillingYear,
		arg.BillingMonth,
		arg.PaymentStatus,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBillsRow
	for rows.Next() {
		var i ListBillsRow
		if err := rows.Scan(
			&i.ID,
			&i.BillCode,
			&i.DepartmentID,
			&i.UtilityType,
			&i.BillingMonth,
			&i.BillingYear,
			&i.Provider,
			&i.ServiceNumber,
			&i.ServiceBreakdown,
			&i.InvoiceNumber,
			&i.InvoiceDate,
			&i.LocationType,
			&i.UsageAmount,
			&i.InvoiceAmount,
			&i.EstimatedAmount,
			&i.ReceivedDate,
			&i.SentToDisbursingDate,
			&i.DisbursingReceivedDate,
			&i.PaymentDate,
			&i.PaymentDocNumber,
			&i.DocType,
			&i.AccountCode,
			&i.BudgetCode,
			&i.FundSource,
			&i.PaidAmount,
			&i.PaymentStatus,
			&i.InvoiceStatus,
			&i.ReceiptNumber,
			&i.ReceiptDate,
			&i.ReceiptPaymentDate,
			&i.AttachmentInvoice,
			&i.AttachmentReceipt,
			&i.AttachmentPaymentDoc,
			&i.AttachmentDirectPayment,
			&i.AttachmentKtbReport,
			&i.IsPendingBillOnly,
			&i.DepositUnitID,
			&i.IsReviewed,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DepartmentName,
			&i.DepartmentShortName,
			&i.DepartmentCostCenter,
			&i.DepositUnitName,
			&i.AuditID,
			&i.AuditStatus,
			&i.IsLateReceive,
			&i.IsLatePayment,
			&i.IsOverdueMoreThan2Months,
			&i.IsDisbursementOver2Months,
			&i.IsWrongMonth,
			&i.IsPhoneOverLimit,
			&i.IsPhoneUsageOverLimit,
			&i.IsWrongBudget,
			&i.IsDuplicate,
			&i.IsAnomalyExpense,
			&i.IsManualAnomaly,
			&i.ManualAnomalyReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBillReviewed = `-- name: MarkBillReviewed :one
UPDATE utility_bills
SET is_reviewed = $2, reviewed_by = $3, reviewed_at = NOW(), updated_at = NOW()
WHERE id = $1
RETURNING id, bill_code, department_id, utility_type, billing_month, billing_year, provider, service_number, service_breakdown, invoice_number, invoice_date, location_type, usage_amount, invoice_amount, estimated_amount, received_date, sent_to_disbursing_date, disbursing_received_date, payment_date, payment_doc_number, doc_type, account_code, budget_code, fund_source, paid_amount, payment_status, invoice_status, receipt_number, receipt_date, receipt_payment_date, attachment_invoice, attachment_receipt, attachment_payment_doc, attachment_direct_payment, attachment_ktb_report, is_pending_bill_only, deposit_unit_id, is_reviewed, reviewed_by, reviewed_at, created_by, created_at, updated_at
`

type MarkBillReviewedParams struct {
	ID         string      `json:"id"`
	IsReviewed pgtype.Bool `json:"is_reviewed"`
	ReviewedBy pgtype.Text `json:"reviewed_by"`
}

func (q *Queries) MarkBillReviewed(ctx context.Context, arg MarkBillReviewedParams) (UtilityBill, error) {
	row := q.db.QueryRow(ctx, markBillReviewed, arg.ID, arg.IsReviewed, arg.ReviewedBy)
	var i UtilityBill
	err := row.Scan(
		&i.ID,
		&i.BillCode,
		&i.DepartmentID,
		&i.UtilityType,
		&i.BillingMonth,
		&i.BillingYear,
		&i.Provider,
		&i.ServiceNumber,
		&i.ServiceBreakdown,
		&i.InvoiceNumber,
		&i.InvoiceDate,
		&i.LocationType,
		&i.UsageAmount,
		&i.InvoiceAmount,
		&i.EstimatedAmount,
		&i.ReceivedDate,
		&i.SentToDisbursingDate,
		&i.DisbursingReceivedDate,
		&i.PaymentDate,
		&i.PaymentDocNumber,
		&i.DocType,
		&i.AccountCode,
		&i.BudgetCode,
		&i.FundSource,
		&i.PaidAmount,
		&i.PaymentStatus,
		&i.InvoiceStatus,
		&i.ReceiptNumber,
		&i.ReceiptDate,
		&i.ReceiptPaymentDate,
		&i.AttachmentInvoice,
		&i.AttachmentReceipt,
		&i.AttachmentPaymentDoc,
		&i.AttachmentDirectPayment,
		&i.AttachmentKtbReport,
		&i.IsPendingBillOnly,
		&i.DepositUnitID,
		&i.IsReviewed,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBill = `-- name: UpdateBill :one
UPDATE utility_bills
SET
    bill_code = $2,
    department_id = $3,
    utility_type = $4,
    billing_month = $5,
    billing_year = $6,
    provider = $7,
    service_number = $8,
    service_breakdown = $9,
    invoice_number = $10,
    invoice_date = $11,
    location_type = $12,
    usage_amount = $13,
    invoice_amount = $14,
    estimated_amount = $15,
    received_date = $16,
    sent_to_disbursing_date = $17,
    disbursing_received_date = $18,
    payment_date = $19,
    payment_doc_number = $20,
    doc_type = $21,
    account_code = $22,
    budget_code = $23,
    fund_source = $24,
    paid_amount = $25,
    payment_status = $26,
    invoice_status = $27,
    receipt_number = $28,
    receipt_date = $29,
    receipt_payment_date = $30,
    attachment_invoice = $31,
    attachment_receipt = $32,
    attachment_payment_doc = $33,
    attachment_direct_payment = $34,
    attachment_ktb_report = $35,
    is_pending_bill_only = $36,
    deposit_unit_id = $37,
    updated_at = NOW()
WHERE id = $1
RETURNING id, bill_code, department_id, utility_type, billing_month, billing_year, provider, service_number, service_breakdown, invoice_number, invoice_date, location_type, usage_amount, invoice_amount, estimated_amount, received_date, sent_to_disbursing_date, disbursing_received_date, payment_date, payment_doc_number, doc_type, account_code, budget_code, fund_source, paid_amount, payment_status, invoice_status, receipt_number, receipt_date, receipt_payment_date, attachment_invoice, attachment_receipt, attachment_payment_doc, attachment_direct_payment, attachment_ktb_report, is_pending_bill_only, deposit_unit_id, is_reviewed, reviewed_by, reviewed_at, created_by, created_at, updated_at
`

type UpdateBillParams struct {
	ID                      string             `json:"id"`
	BillCode                pgtype.Text        `json:"bill_code"`
	DepartmentID            string             `json:"department_id"`
	UtilityType             string             `json:"utility_type"`
	BillingMonth            int32              `json:"billing_month"`
	BillingYear             int32              `json:"billing_year"`
	Provider                pgtype.Text        `json:"provider"`
	ServiceNumber           pgtype.Text        `json:"service_number"`
	ServiceBreakdown        pgtype.Text        `json:"service_breakdown"`
	InvoiceNumber           pgtype.Text        `json:"invoice_number"`
	InvoiceDate             pgtype.Timestamptz `json:"invoice_date"`
	LocationType            pgtype.Text        `json:"location_type"`
	UsageAmount             pgtype.Numeric     `json:"usage_amount"`
	InvoiceAmount           pgtype.Numeric     `json:"invoice_amount"`
	EstimatedAmount         pgtype.Numeric     `json:"estimated_amount"`
	ReceivedDate            pgtype.Timestamptz `json:"received_date"`
	SentToDisbursingDate    pgtype.Timestamptz `json:"sent_to_disbursing_date"`
	DisbursingReceivedDate  pgtype.Timestamptz `json:"disbursing_received_date"`
	PaymentDate             pgtype.Timestamptz `json:"payment_date"`
	PaymentDocNumber        pgtype.Text        `json:"payment_doc_number"`
	DocType                 pgtype.Text        `json:"doc_type"`
	AccountCode             pgtype.Text        `json:"account_code"`
	BudgetCode              pgtype.Text        `json:"budget_code"`
	FundSource              pgtype.Text        `json:"fund_source"`
	PaidAmount              pgtype.Numeric     `json:"paid_amount"`
	PaymentStatus           string             `json:"payment_status"`
	InvoiceStatus           string             `json:"invoice_status"`
	ReceiptNumber           pgtype.Text        `json:"receipt_number"`
	ReceiptDate             pgtype.Timestamptz `json:"receipt_date"`
	ReceiptPaymentDate      pgtype.Timestamptz `json:"receipt_payment_date"`
	AttachmentInvoice       pgtype.Text        `json:"attachment_invoice"`
	AttachmentReceipt       pgtype.Text        `json:"attachment_receipt"`
	AttachmentPaymentDoc    pgtype.Text        `json:"attachment_payment_doc"`
	AttachmentDirectPayment pgtype.Text        `json:"attachment_direct_payment"`
	AttachmentKtbReport     pgtype.Text        `json:"attachment_ktb_report"`
	IsPendingBillOnly       bool               `json:"is_pending_bill_only"`
	DepositUnitID           pgtype.Text        `json:"deposit_unit_id"`
}

func (q *Queries) UpdateBill(ctx context.Context, arg UpdateBillParams) (UtilityBill, error) {
	row := q.db.QueryRow(ctx, updateBill,
		arg.ID,
		arg.BillCode,
		arg.DepartmentID,
		arg.UtilityType,
		arg.BillingMonth,
		arg.BillingYear,
		arg.Provider,
		arg.ServiceNumber,
		arg.ServiceBreakdown,
		arg.InvoiceNumber,
		arg.InvoiceDate,
		arg.LocationType,
		arg.UsageAmount,
		arg.InvoiceAmount,
		arg.EstimatedAmount,
		arg.ReceivedDate,
		arg.SentToDisbursingDate,
		arg.DisbursingReceivedDate,
		arg.PaymentDate,
		arg.PaymentDocNumber,
		arg.DocType,
		arg.AccountCode,
		arg.BudgetCode,
		arg.FundSource,
		arg.PaidAmount,
		arg.PaymentStatus,
		arg.InvoiceStatus,
		arg.ReceiptNumber,
		arg.ReceiptDate,
		arg.ReceiptPaymentDate,
		arg.AttachmentInvoice,
		arg.AttachmentReceipt,
		arg.AttachmentPaymentDoc,
		arg.AttachmentDirectPayment,
		arg.AttachmentKtbReport,
		arg.IsPendingBillOnly,
		arg.DepositUnitID,
	)
	var i UtilityBill
	err := row.Scan(
		&i.ID,
		&i.BillCode,
		&i.DepartmentID,
		&i.UtilityType,
		&i.BillingMonth,
		&i.BillingYear,
		&i.Provider,
		&i.ServiceNumber,
		&i.ServiceBreakdown,
		&i.InvoiceNumber,
		&i.InvoiceDate,
		&i.LocationType,
		&i.UsageAmount,
		&i.InvoiceAmount,
		&i.EstimatedAmount,
		&i.ReceivedDate,
		&i.SentToDisbursingDate,
		&i.DisbursingReceivedDate,
		&i.PaymentDate,
		&i.PaymentDocNumber,
		&i.DocType,
		&i.AccountCode,
		&i.BudgetCode,
		&i.FundSource,
		&i.PaidAmount,
		&i.PaymentStatus,
		&i.InvoiceStatus,
		&i.ReceiptNumber,
		&i.ReceiptDate,
		&i.ReceiptPaymentDate,
		&i.AttachmentInvoice,
		&i.AttachmentReceipt,
		&i.AttachmentPaymentDoc,
		&i.AttachmentDirectPayment,
		&i.AttachmentKtbReport,
		&i.IsPendingBillOnly,
		&i.DepositUnitID,
		&i.IsReviewed,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
