// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: budgets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBudget = `-- name: CreateBudget :one
INSERT INTO budgets (
    id, budget_code, name, fund_source, allocated_amount, transferred_amount,
    department_id, fiscal_year, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW()
)
RETURNING id, budget_code, name, fund_source, allocated_amount, transferred_amount, department_id, fiscal_year, created_at, updated_at
`

type CreateBudgetParams struct {
	ID                string         `json:"id"`
	BudgetCode        string         `json:"budget_code"`
	Name              string         `json:"name"`
	FundSource        pgtype.Text    `json:"fund_source"`
	AllocatedAmount   pgtype.Numeric `json:"allocated_amount"`
	TransferredAmount pgtype.Numeric `json:"transferred_amount"`
	DepartmentID      string         `json:"department_id"`
	FiscalYear        int32          `json:"fiscal_year"`
}

func (q *Queries) CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, createBudget,
		arg.ID,
		arg.BudgetCode,
		arg.Name,
		arg.FundSource,
		arg.AllocatedAmount,
		arg.TransferredAmount,
		arg.DepartmentID,
		arg.FiscalYear,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.BudgetCode,
		&i.Name,
		&i.FundSource,
		&i.AllocatedAmount,
		&i.TransferredAmount,
		&i.DepartmentID,
		&i.FiscalYear,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBudgetCode = `-- name: CreateBudgetCode :one
INSERT INTO budget_codes (
    id, code, name, fiscal_year, description, is_active, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, NOW(), NOW()
)
RETURNING id, code, name, fiscal_year, description, is_active, created_at, updated_at
`

type CreateBudgetCodeParams struct {
	ID          string      `json:"id"`
	Code        string      `json:"code"`
	Name        string      `json:"name"`
	FiscalYear  int32       `json:"fiscal_year"`
	Description pgtype.Text `json:"description"`
	IsActive    bool        `json:"is_active"`
}

func (q *Queries) CreateBudgetCode(ctx context.Context, arg CreateBudgetCodeParams) (BudgetCode, error) {
	row := q.db.QueryRow(ctx, createBudgetCode,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.FiscalYear,
		arg.Description,
		arg.IsActive,
	)
	var i BudgetCode
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.FiscalYear,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBudget = `-- name: DeleteBudget :exec
DELETE FROM budgets
WHERE id = $1
`

func (q *Queries) DeleteBudget(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteBudget, id)
	return err
}

const getBudgetByID = `-- name: GetBudgetByID :one
SELECT id, budget_code, name, fund_source, allocated_amount, transferred_amount, department_id, fiscal_year, created_at, updated_at FROM budgets
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBudgetByID(ctx context.Context, id string) (Budget, error) {
	row := q.db.QueryRow(ctx, getBudgetByID, id)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.BudgetCode,
		&i.Name,
		&i.FundSource,
		&i.AllocatedAmount,
		&i.TransferredAmount,
		&i.DepartmentID,
		&i.FiscalYear,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBudgetCodes = `-- name: ListBudgetCodes :many
SELECT id, code, name, fiscal_year, description, is_active, created_at, updated_at FROM budget_codes
WHERE ($1::int IS NULL OR fiscal_year = $1)
ORDER BY code ASC
`

// Budget Codes
func (q *Queries) ListBudgetCodes(ctx context.Context, fiscalYear pgtype.Int4) ([]BudgetCode, error) {
	rows, err := q.db.Query(ctx, listBudgetCodes, fiscalYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BudgetCode
	for rows.Next() {
		var i BudgetCode
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.FiscalYear,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBudgets = `-- name: ListBudgets :many
SELECT b.id, b.budget_code, b.name, b.fund_source, b.allocated_amount, b.transferred_amount, b.department_id, b.fiscal_year, b.created_at, b.updated_at, d.full_name AS department_name
FROM budgets b
JOIN departments d ON b.department_id = d.id
WHERE ($1::int IS NULL OR b.fiscal_year = $1)
  AND ($2::text IS NULL OR b.department_id = $2)
ORDER BY b.fiscal_year DESC, d.full_name ASC
`

type ListBudgetsParams struct {
	FiscalYear   pgtype.Int4 `json:"fiscal_year"`
	DepartmentID pgtype.Text `json:"department_id"`
}

type ListBudgetsRow struct {
	ID                string             `json:"id"`
	BudgetCode        string             `json:"budget_code"`
	Name              string             `json:"name"`
	FundSource        pgtype.Text        `json:"fund_source"`
	AllocatedAmount   pgtype.Numeric     `json:"allocated_amount"`
	TransferredAmount pgtype.Numeric     `json:"transferred_amount"`
	DepartmentID      string             `json:"department_id"`
	FiscalYear        int32              `json:"fiscal_year"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DepartmentName    string             `json:"department_name"`
}

func (q *Queries) ListBudgets(ctx context.Context, arg ListBudgetsParams) ([]ListBudgetsRow, error) {
	rows, err := q.db.Query(ctx, listBudgets, arg.FiscalYear, arg.DepartmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBudgetsRow
	for rows.Next() {
		var i ListBudgetsRow
		if err := rows.Scan(
			&i.ID,
			&i.BudgetCode,
			&i.Name,
			&i.FundSource,
			&i.AllocatedAmount,
			&i.TransferredAmount,
			&i.DepartmentID,
			&i.FiscalYear,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DepartmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBudget = `-- name: UpdateBudget :one
UPDATE budgets
SET 
    budget_code = $2,
    name = $3,
    fund_source = $4,
    allocated_amount = $5,
    transferred_amount = $6,
    fiscal_year = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, budget_code, name, fund_source, allocated_amount, transferred_amount, department_id, fiscal_year, created_at, updated_at
`

type UpdateBudgetParams struct {
	ID                string         `json:"id"`
	BudgetCode        string         `json:"budget_code"`
	Name              string         `json:"name"`
	FundSource        pgtype.Text    `json:"fund_source"`
	AllocatedAmount   pgtype.Numeric `json:"allocated_amount"`
	TransferredAmount pgtype.Numeric `json:"transferred_amount"`
	FiscalYear        int32          `json:"fiscal_year"`
}

func (q *Queries) UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, updateBudget,
		arg.ID,
		arg.BudgetCode,
		arg.Name,
		arg.FundSource,
		arg.AllocatedAmount,
		arg.TransferredAmount,
		arg.FiscalYear,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.BudgetCode,
		&i.Name,
		&i.FundSource,
		&i.AllocatedAmount,
		&i.TransferredAmount,
		&i.DepartmentID,
		&i.FiscalYear,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
