// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: departments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDepartment = `-- name: CreateDepartment :one
INSERT INTO departments (
    id, cost_center_code, disbursing_unit, deposit_unit,
    full_name, short_name, division, location, province,
    responsible_person, phone, responsible_phone, email, type,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, NOW(), NOW()
)
RETURNING id, cost_center_code, disbursing_unit, deposit_unit, full_name, short_name, division, location, province, responsible_person, phone, responsible_phone, email, type, created_at, updated_at
`

type CreateDepartmentParams struct {
	ID                string      `json:"id"`
	CostCenterCode    pgtype.Text `json:"cost_center_code"`
	DisbursingUnit    pgtype.Text `json:"disbursing_unit"`
	DepositUnit       pgtype.Text `json:"deposit_unit"`
	FullName          string      `json:"full_name"`
	ShortName         pgtype.Text `json:"short_name"`
	Division          pgtype.Text `json:"division"`
	Location          pgtype.Text `json:"location"`
	Province          pgtype.Text `json:"province"`
	ResponsiblePerson pgtype.Text `json:"responsible_person"`
	Phone             pgtype.Text `json:"phone"`
	ResponsiblePhone  pgtype.Text `json:"responsible_phone"`
	Email             pgtype.Text `json:"email"`
	Type              pgtype.Text `json:"type"`
}

func (q *Queries) CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, createDepartment,
		arg.ID,
		arg.CostCenterCode,
		arg.DisbursingUnit,
		arg.DepositUnit,
		arg.FullName,
		arg.ShortName,
		arg.Division,
		arg.Location,
		arg.Province,
		arg.ResponsiblePerson,
		arg.Phone,
		arg.ResponsiblePhone,
		arg.Email,
		arg.Type,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.CostCenterCode,
		&i.DisbursingUnit,
		&i.DepositUnit,
		&i.FullName,
		&i.ShortName,
		&i.Division,
		&i.Location,
		&i.Province,
		&i.ResponsiblePerson,
		&i.Phone,
		&i.ResponsiblePhone,
		&i.Email,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDepartmentService = `-- name: CreateDepartmentService :one
INSERT INTO department_services (
    id, department_id, utility_type, provider, service_number,
    location_type, phone_owner_name, phone_owner_position,
    phone_reimbursement_limit, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, NOW(), NOW()
)
RETURNING id, department_id, utility_type, provider, service_number, location_type, phone_owner_name, phone_owner_position, phone_reimbursement_limit, created_at, updated_at
`

type CreateDepartmentServiceParams struct {
	ID                      string      `json:"id"`
	DepartmentID            string      `json:"department_id"`
	UtilityType             string      `json:"utility_type"`
	Provider                string      `json:"provider"`
	ServiceNumber           string      `json:"service_number"`
	LocationType            pgtype.Text `json:"location_type"`
	PhoneOwnerName          pgtype.Text `json:"phone_owner_name"`
	PhoneOwnerPosition      pgtype.Text `json:"phone_owner_position"`
	PhoneReimbursementLimit pgtype.Int4 `json:"phone_reimbursement_limit"`
}

func (q *Queries) CreateDepartmentService(ctx context.Context, arg CreateDepartmentServiceParams) (DepartmentService, error) {
	row := q.db.QueryRow(ctx, createDepartmentService,
		arg.ID,
		arg.DepartmentID,
		arg.UtilityType,
		arg.Provider,
		arg.ServiceNumber,
		arg.LocationType,
		arg.PhoneOwnerName,
		arg.PhoneOwnerPosition,
		arg.PhoneReimbursementLimit,
	)
	var i DepartmentService
	err := row.Scan(
		&i.ID,
		&i.DepartmentID,
		&i.UtilityType,
		&i.Provider,
		&i.ServiceNumber,
		&i.LocationType,
		&i.PhoneOwnerName,
		&i.PhoneOwnerPosition,
		&i.PhoneReimbursementLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDepartment = `-- name: DeleteDepartment :exec
DELETE FROM departments
WHERE id = $1
`

func (q *Queries) DeleteDepartment(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteDepartment, id)
	return err
}

const deleteDepartmentService = `-- name: DeleteDepartmentService :exec
DELETE FROM department_services
WHERE id = $1
`

func (q *Queries) DeleteDepartmentService(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteDepartmentService, id)
	return err
}

const getDepartmentByID = `-- name: GetDepartmentByID :one
SELECT id, cost_center_code, disbursing_unit, deposit_unit, full_name, short_name, division, location, province, responsible_person, phone, responsible_phone, email, type, created_at, updated_at FROM departments
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDepartmentByID(ctx context.Context, id string) (Department, error) {
	row := q.db.QueryRow(ctx, getDepartmentByID, id)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.CostCenterCode,
		&i.DisbursingUnit,
		&i.DepositUnit,
		&i.FullName,
		&i.ShortName,
		&i.Division,
		&i.Location,
		&i.Province,
		&i.ResponsiblePerson,
		&i.Phone,
		&i.ResponsiblePhone,
		&i.Email,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllDepartmentServices = `-- name: ListAllDepartmentServices :many
SELECT id, department_id, utility_type, provider, service_number, location_type, phone_owner_name, phone_owner_position, phone_reimbursement_limit, created_at, updated_at FROM department_services
ORDER BY department_id, utility_type ASC
`

func (q *Queries) ListAllDepartmentServices(ctx context.Context) ([]DepartmentService, error) {
	rows, err := q.db.Query(ctx, listAllDepartmentServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DepartmentService
	for rows.Next() {
		var i DepartmentService
		if err := rows.Scan(
			&i.ID,
			&i.DepartmentID,
			&i.UtilityType,
			&i.Provider,
			&i.ServiceNumber,
			&i.LocationType,
			&i.PhoneOwnerName,
			&i.PhoneOwnerPosition,
			&i.PhoneReimbursementLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepartmentServices = `-- name: ListDepartmentServices :many
SELECT id, department_id, utility_type, provider, service_number, location_type, phone_owner_name, phone_owner_position, phone_reimbursement_limit, created_at, updated_at FROM department_services
WHERE department_id = $1
ORDER BY utility_type, service_number ASC
`

// Department Services
func (q *Queries) ListDepartmentServices(ctx context.Context, departmentID string) ([]DepartmentService, error) {
	rows, err := q.db.Query(ctx, listDepartmentServices, departmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DepartmentService
	for rows.Next() {
		var i DepartmentService
		if err := rows.Scan(
			&i.ID,
			&i.DepartmentID,
			&i.UtilityType,
			&i.Provider,
			&i.ServiceNumber,
			&i.LocationType,
			&i.PhoneOwnerName,
			&i.PhoneOwnerPosition,
			&i.PhoneReimbursementLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDepartments = `-- name: ListDepartments :many
SELECT id, cost_center_code, disbursing_unit, deposit_unit, full_name, short_name, division, location, province, responsible_person, phone, responsible_phone, email, type, created_at, updated_at FROM departments
ORDER BY full_name ASC
`

func (q *Queries) ListDepartments(ctx context.Context) ([]Department, error) {
	rows, err := q.db.Query(ctx, listDepartments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Department
	for rows.Next() {
		var i Department
		if err := rows.Scan(
			&i.ID,
			&i.CostCenterCode,
			&i.DisbursingUnit,
			&i.DepositUnit,
			&i.FullName,
			&i.ShortName,
			&i.Division,
			&i.Location,
			&i.Province,
			&i.ResponsiblePerson,
			&i.Phone,
			&i.ResponsiblePhone,
			&i.Email,
			&i.Type,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDepartment = `-- name: UpdateDepartment :one
UPDATE departments
SET 
    cost_center_code = $2,
    disbursing_unit = $3,
    deposit_unit = $4,
    full_name = $5,
    short_name = $6,
    division = $7,
    location = $8,
    province = $9,
    responsible_person = $10,
    phone = $11,
    responsible_phone = $12,
    email = $13,
    type = $14,
    updated_at = NOW()
WHERE id = $1
RETURNING id, cost_center_code, disbursing_unit, deposit_unit, full_name, short_name, division, location, province, responsible_person, phone, responsible_phone, email, type, created_at, updated_at
`

type UpdateDepartmentParams struct {
	ID                string      `json:"id"`
	CostCenterCode    pgtype.Text `json:"cost_center_code"`
	DisbursingUnit    pgtype.Text `json:"disbursing_unit"`
	DepositUnit       pgtype.Text `json:"deposit_unit"`
	FullName          string      `json:"full_name"`
	ShortName         pgtype.Text `json:"short_name"`
	Division          pgtype.Text `json:"division"`
	Location          pgtype.Text `json:"location"`
	Province          pgtype.Text `json:"province"`
	ResponsiblePerson pgtype.Text `json:"responsible_person"`
	Phone             pgtype.Text `json:"phone"`
	ResponsiblePhone  pgtype.Text `json:"responsible_phone"`
	Email             pgtype.Text `json:"email"`
	Type              pgtype.Text `json:"type"`
}

func (q *Queries) UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error) {
	row := q.db.QueryRow(ctx, updateDepartment,
		arg.ID,
		arg.CostCenterCode,
		arg.DisbursingUnit,
		arg.DepositUnit,
		arg.FullName,
		arg.ShortName,
		arg.Division,
		arg.Location,
		arg.Province,
		arg.ResponsiblePerson,
		arg.Phone,
		arg.ResponsiblePhone,
		arg.Email,
		arg.Type,
	)
	var i Department
	err := row.Scan(
		&i.ID,
		&i.CostCenterCode,
		&i.DisbursingUnit,
		&i.DepositUnit,
		&i.FullName,
		&i.ShortName,
		&i.Division,
		&i.Location,
		&i.Province,
		&i.ResponsiblePerson,
		&i.Phone,
		&i.ResponsiblePhone,
		&i.Email,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
