// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Audit struct {
	ID                        string             `json:"id"`
	UtilityBillID             string             `json:"utility_bill_id"`
	AuditorID                 string             `json:"auditor_id"`
	IsLateReceive             pgtype.Bool        `json:"is_late_receive"`
	IsLatePayment             pgtype.Bool        `json:"is_late_payment"`
	IsOverdueMoreThan2Months  pgtype.Bool        `json:"is_overdue_more_than_2_months"`
	IsDisbursementOver2Months pgtype.Bool        `json:"is_disbursement_over_2_months"`
	IsWrongMonth              pgtype.Bool        `json:"is_wrong_month"`
	IsPhoneOverLimit          pgtype.Bool        `json:"is_phone_over_limit"`
	IsPhoneUsageOverLimit     pgtype.Bool        `json:"is_phone_usage_over_limit"`
	IsWrongBudget             pgtype.Bool        `json:"is_wrong_budget"`
	IsDuplicate               pgtype.Bool        `json:"is_duplicate"`
	IsAnomalyExpense          pgtype.Bool        `json:"is_anomaly_expense"`
	IsManualAnomaly           pgtype.Bool        `json:"is_manual_anomaly"`
	Status                    string             `json:"status"`
	Remarks                   pgtype.Text        `json:"remarks"`
	ManualAnomalyReason       pgtype.Text        `json:"manual_anomaly_reason"`
	AttachmentProof           pgtype.Text        `json:"attachment_proof"`
	CreatedAt                 pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `json:"updated_at"`
}

type BillActivityLog struct {
	ID        string             `json:"id"`
	BillID    string             `json:"bill_id"`
	UserID    string             `json:"user_id"`
	Action    string             `json:"action"`
	Details   pgtype.Text        `json:"details"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Budget struct {
	ID                string             `json:"id"`
	BudgetCode        string             `json:"budget_code"`
	Name              string             `json:"name"`
	FundSource        pgtype.Text        `json:"fund_source"`
	AllocatedAmount   pgtype.Numeric     `json:"allocated_amount"`
	TransferredAmount pgtype.Numeric     `json:"transferred_amount"`
	DepartmentID      string             `json:"department_id"`
	FiscalYear        int32              `json:"fiscal_year"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type BudgetCode struct {
	ID          string             `json:"id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	FiscalYear  int32              `json:"fiscal_year"`
	Description pgtype.Text        `json:"description"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Department struct {
	ID                string             `json:"id"`
	CostCenterCode    pgtype.Text        `json:"cost_center_code"`
	DisbursingUnit    pgtype.Text        `json:"disbursing_unit"`
	DepositUnit       pgtype.Text        `json:"deposit_unit"`
	FullName          string             `json:"full_name"`
	ShortName         pgtype.Text        `json:"short_name"`
	Division          pgtype.Text        `json:"division"`
	Location          pgtype.Text        `json:"location"`
	Province          pgtype.Text        `json:"province"`
	ResponsiblePerson pgtype.Text        `json:"responsible_person"`
	Phone             pgtype.Text        `json:"phone"`
	ResponsiblePhone  pgtype.Text        `json:"responsible_phone"`
	Email             pgtype.Text        `json:"email"`
	Type              pgtype.Text        `json:"type"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type DepartmentService struct {
	ID                      string             `json:"id"`
	DepartmentID            string             `json:"department_id"`
	UtilityType             string             `json:"utility_type"`
	Provider                string             `json:"provider"`
	ServiceNumber           string             `json:"service_number"`
	LocationType            pgtype.Text        `json:"location_type"`
	PhoneOwnerName          pgtype.Text        `json:"phone_owner_name"`
	PhoneOwnerPosition      pgtype.Text        `json:"phone_owner_position"`
	PhoneReimbursementLimit pgtype.Int4        `json:"phone_reimbursement_limit"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type Notification struct {
	ID           string             `json:"id"`
	DepartmentID pgtype.Text        `json:"department_id"`
	TargetRole   pgtype.Text        `json:"target_role"`
	Title        string             `json:"title"`
	Message      string             `json:"message"`
	Type         string             `json:"type"`
	Severity     string             `json:"severity"`
	IsRead       bool               `json:"is_read"`
	Link         pgtype.Text        `json:"link"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID            string             `json:"id"`
	Name          string             `json:"name"`
	Email         string             `json:"email"`
	PasswordHash  string             `json:"password_hash"`
	EmailVerified bool               `json:"email_verified"`
	Image         pgtype.Text        `json:"image"`
	Role          string             `json:"role"`
	Banned        pgtype.Bool        `json:"banned"`
	BanReason     pgtype.Text        `json:"ban_reason"`
	BanExpires    pgtype.Timestamptz `json:"ban_expires"`
	DepartmentID  pgtype.Text        `json:"department_id"`
	Phone         pgtype.Text        `json:"phone"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type UtilityBill struct {
	ID                      string             `json:"id"`
	BillCode                pgtype.Text        `json:"bill_code"`
	DepartmentID            string             `json:"department_id"`
	UtilityType             string             `json:"utility_type"`
	BillingMonth            int32              `json:"billing_month"`
	BillingYear             int32              `json:"billing_year"`
	Provider                pgtype.Text        `json:"provider"`
	ServiceNumber           pgtype.Text        `json:"service_number"`
	ServiceBreakdown        pgtype.Text        `json:"service_breakdown"`
	InvoiceNumber           pgtype.Text        `json:"invoice_number"`
	InvoiceDate             pgtype.Timestamptz `json:"invoice_date"`
	LocationType            pgtype.Text        `json:"location_type"`
	UsageAmount             pgtype.Numeric     `json:"usage_amount"`
	InvoiceAmount           pgtype.Numeric     `json:"invoice_amount"`
	EstimatedAmount         pgtype.Numeric     `json:"estimated_amount"`
	ReceivedDate            pgtype.Timestamptz `json:"received_date"`
	SentToDisbursingDate    pgtype.Timestamptz `json:"sent_to_disbursing_date"`
	DisbursingReceivedDate  pgtype.Timestamptz `json:"disbursing_received_date"`
	PaymentDate             pgtype.Timestamptz `json:"payment_date"`
	PaymentDocNumber        pgtype.Text        `json:"payment_doc_number"`
	DocType                 pgtype.Text        `json:"doc_type"`
	AccountCode             pgtype.Text        `json:"account_code"`
	BudgetCode              pgtype.Text        `json:"budget_code"`
	FundSource              pgtype.Text        `json:"fund_source"`
	PaidAmount              pgtype.Numeric     `json:"paid_amount"`
	PaymentStatus           string             `json:"payment_status"`
	InvoiceStatus           string             `json:"invoice_status"`
	ReceiptNumber           pgtype.Text        `json:"receipt_number"`
	ReceiptDate             pgtype.Timestamptz `json:"receipt_date"`
	ReceiptPaymentDate      pgtype.Timestamptz `json:"receipt_payment_date"`
	AttachmentInvoice       pgtype.Text        `json:"attachment_invoice"`
	AttachmentReceipt       pgtype.Text        `json:"attachment_receipt"`
	AttachmentPaymentDoc    pgtype.Text        `json:"attachment_payment_doc"`
	AttachmentDirectPayment pgtype.Text        `json:"attachment_direct_payment"`
	AttachmentKtbReport     pgtype.Text        `json:"attachment_ktb_report"`
	IsPendingBillOnly       bool               `json:"is_pending_bill_only"`
	DepositUnitID           pgtype.Text        `json:"deposit_unit_id"`
	IsReviewed              pgtype.Bool        `json:"is_reviewed"`
	ReviewedBy              pgtype.Text        `json:"reviewed_by"`
	ReviewedAt              pgtype.Timestamptz `json:"reviewed_at"`
	CreatedBy               string             `json:"created_by"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}
