// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    id, department_id, target_role, title, message, type,
    severity, is_read, link, created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, NOW(), NOW()
)
RETURNING id, department_id, target_role, title, message, type, severity, is_read, link, created_at, updated_at
`

type CreateNotificationParams struct {
	ID           string      `json:"id"`
	DepartmentID pgtype.Text `json:"department_id"`
	TargetRole   pgtype.Text `json:"target_role"`
	Title        string      `json:"title"`
	Message      string      `json:"message"`
	Type         string      `json:"type"`
	Severity     string      `json:"severity"`
	IsRead       bool        `json:"is_read"`
	Link         pgtype.Text `json:"link"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.ID,
		arg.DepartmentID,
		arg.TargetRole,
		arg.Title,
		arg.Message,
		arg.Type,
		arg.Severity,
		arg.IsRead,
		arg.Link,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.DepartmentID,
		&i.TargetRole,
		&i.Title,
		&i.Message,
		&i.Type,
		&i.Severity,
		&i.IsRead,
		&i.Link,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, department_id, target_role, title, message, type, severity, is_read, link, created_at, updated_at FROM notifications
WHERE ($1::text IS NULL OR department_id = $1)
ORDER BY created_at DESC
LIMIT 100
`

func (q *Queries) ListNotifications(ctx context.Context, departmentID pgtype.Text) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications, departmentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.DepartmentID,
			&i.TargetRole,
			&i.Title,
			&i.Message,
			&i.Type,
			&i.Severity,
			&i.IsRead,
			&i.Link,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications
SET is_read = true, updated_at = NOW()
WHERE ($1::text IS NULL OR department_id = $1)
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, departmentID pgtype.Text) error {
	_, err := q.db.Exec(ctx, markAllNotificationsRead, departmentID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :one
UPDATE notifications
SET is_read = true, updated_at = NOW()
WHERE id = $1
RETURNING id, department_id, target_role, title, message, type, severity, is_read, link, created_at, updated_at
`

func (q *Queries) MarkNotificationRead(ctx context.Context, id string) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationRead, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.DepartmentID,
		&i.TargetRole,
		&i.Title,
		&i.Message,
		&i.Type,
		&i.Severity,
		&i.IsRead,
		&i.Link,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
