// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateBill(ctx context.Context, arg CreateBillParams) (UtilityBill, error)
	CreateBillActivityLog(ctx context.Context, arg CreateBillActivityLogParams) (BillActivityLog, error)
	CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error)
	CreateBudgetCode(ctx context.Context, arg CreateBudgetCodeParams) (BudgetCode, error)
	CreateDepartment(ctx context.Context, arg CreateDepartmentParams) (Department, error)
	CreateDepartmentService(ctx context.Context, arg CreateDepartmentServiceParams) (DepartmentService, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBill(ctx context.Context, id string) error
	DeleteBudget(ctx context.Context, id string) error
	DeleteDepartment(ctx context.Context, id string) error
	DeleteDepartmentService(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id string) error
	FlagManualAnomaly(ctx context.Context, arg FlagManualAnomalyParams) (Audit, error)
	GetAuditByBillID(ctx context.Context, utilityBillID string) (Audit, error)
	GetBillActivityLogs(ctx context.Context, billID string) ([]GetBillActivityLogsRow, error)
	GetBillByID(ctx context.Context, id string) (GetBillByIDRow, error)
	GetBudgetByID(ctx context.Context, id string) (Budget, error)
	GetDepartmentByID(ctx context.Context, id string) (Department, error)
	GetLatestBillCodeForPrefix(ctx context.Context, billCode pgtype.Text) (pgtype.Text, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	ListAllDepartmentServices(ctx context.Context) ([]DepartmentService, error)
	ListAudits(ctx context.Context, status pgtype.Text) ([]ListAuditsRow, error)
	ListBills(ctx context.Context, arg ListBillsParams) ([]ListBillsRow, error)
	// Budget Codes
	ListBudgetCodes(ctx context.Context, fiscalYear pgtype.Int4) ([]BudgetCode, error)
	ListBudgets(ctx context.Context, arg ListBudgetsParams) ([]ListBudgetsRow, error)
	// Department Services
	ListDepartmentServices(ctx context.Context, departmentID string) ([]DepartmentService, error)
	ListDepartments(ctx context.Context) ([]Department, error)
	ListNotifications(ctx context.Context, departmentID pgtype.Text) ([]Notification, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	MarkAllNotificationsRead(ctx context.Context, departmentID pgtype.Text) error
	MarkBillReviewed(ctx context.Context, arg MarkBillReviewedParams) (UtilityBill, error)
	MarkNotificationRead(ctx context.Context, id string) (Notification, error)
	ResolveAudit(ctx context.Context, arg ResolveAuditParams) (Audit, error)
	UnflagManualAnomaly(ctx context.Context, utilityBillID string) (Audit, error)
	UpdateBill(ctx context.Context, arg UpdateBillParams) (UtilityBill, error)
	UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (Budget, error)
	UpdateDepartment(ctx context.Context, arg UpdateDepartmentParams) (Department, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpsertAudit(ctx context.Context, arg UpsertAuditParams) (Audit, error)
}

var _ Querier = (*Queries)(nil)
