// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, name, email, password_hash, email_verified, image, role,
    banned, ban_reason, ban_expires, department_id, phone,
    created_at, updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, NOW(), NOW()
)
RETURNING id, name, email, password_hash, email_verified, image, role, banned, ban_reason, ban_expires, department_id, phone, created_at, updated_at
`

type CreateUserParams struct {
	ID            string             `json:"id"`
	Name          string             `json:"name"`
	Email         string             `json:"email"`
	PasswordHash  string             `json:"password_hash"`
	EmailVerified bool               `json:"email_verified"`
	Image         pgtype.Text        `json:"image"`
	Role          string             `json:"role"`
	Banned        pgtype.Bool        `json:"banned"`
	BanReason     pgtype.Text        `json:"ban_reason"`
	BanExpires    pgtype.Timestamptz `json:"ban_expires"`
	DepartmentID  pgtype.Text        `json:"department_id"`
	Phone         pgtype.Text        `json:"phone"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PasswordHash,
		arg.EmailVerified,
		arg.Image,
		arg.Role,
		arg.Banned,
		arg.BanReason,
		arg.BanExpires,
		arg.DepartmentID,
		arg.Phone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.Image,
		&i.Role,
		&i.Banned,
		&i.BanReason,
		&i.BanExpires,
		&i.DepartmentID,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password_hash, email_verified, image, role, banned, ban_reason, ban_expires, department_id, phone, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.Image,
		&i.Role,
		&i.Banned,
		&i.BanReason,
		&i.BanExpires,
		&i.DepartmentID,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, password_hash, email_verified, image, role, banned, ban_reason, ban_expires, department_id, phone, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.Image,
		&i.Role,
		&i.Banned,
		&i.BanReason,
		&i.BanExpires,
		&i.DepartmentID,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT u.id, u.name, u.email, u.email_verified, u.image, u.role, u.banned, u.ban_reason, u.department_id, u.phone, u.created_at, u.updated_at,
       d.full_name AS department_name
FROM users u
LEFT JOIN departments d ON u.department_id = d.id
ORDER BY u.created_at DESC
`

type ListUsersRow struct {
	ID             string             `json:"id"`
	Name           string             `json:"name"`
	Email          string             `json:"email"`
	EmailVerified  bool               `json:"email_verified"`
	Image          pgtype.Text        `json:"image"`
	Role           string             `json:"role"`
	Banned         pgtype.Bool        `json:"banned"`
	BanReason      pgtype.Text        `json:"ban_reason"`
	DepartmentID   pgtype.Text        `json:"department_id"`
	Phone          pgtype.Text        `json:"phone"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DepartmentName pgtype.Text        `json:"department_name"`
}

func (q *Queries) ListUsers(ctx context.Context) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.EmailVerified,
			&i.Image,
			&i.Role,
			&i.Banned,
			&i.BanReason,
			&i.DepartmentID,
			&i.Phone,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DepartmentName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users
SET password_hash = $2, updated_at = NOW()
WHERE id = $1
`

type UpdatePasswordParams struct {
	ID           string `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.Exec(ctx, updatePassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET 
    name = $2,
    role = $3,
    department_id = $4,
    phone = $5,
    banned = $6,
    ban_reason = $7,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, email, password_hash, email_verified, image, role, banned, ban_reason, ban_expires, department_id, phone, created_at, updated_at
`

type UpdateUserParams struct {
	ID           string      `json:"id"`
	Name         string      `json:"name"`
	Role         string      `json:"role"`
	DepartmentID pgtype.Text `json:"department_id"`
	Phone        pgtype.Text `json:"phone"`
	Banned       pgtype.Bool `json:"banned"`
	BanReason    pgtype.Text `json:"ban_reason"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Role,
		arg.DepartmentID,
		arg.Phone,
		arg.Banned,
		arg.BanReason,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PasswordHash,
		&i.EmailVerified,
		&i.Image,
		&i.Role,
		&i.Banned,
		&i.BanReason,
		&i.BanExpires,
		&i.DepartmentID,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
